export const APP_ROUTES = {
  HOME: { title: 'Keystone Woodworx Dashboard', path: '/' },
  ABOUT: { title: 'About Us', path: '/about-us' },
  PROJECTS: { title: 'Our Projects', path: '/projects' },
  BLOG: { title: 'Blog', path: '/blog' },
  CONTACT: { title: 'Contact Us', path: '/contact' },
  SERVICES: {
    CABINETRY: { title: 'Cabinetry Services', path: '/cabinetry' },
    REMODELS: { title: 'Home Remodels', path: '/remodels' },
    CLOSETS: { title: 'Closet Solutions', path: '/closets' },
    CUSTOM: { title: 'Custom Work', path: '/custom' },
  },
  AUTH: {
    LOGIN: { title: 'Login', path: '/auth/login' },
    REGISTER: { title: 'Register', path: '/auth/register' },
    OTP: { title: 'One-Time Password', path: '/auth/otp' },
    FORGOT_PASSWORD: { title: 'Forgot Password', path: '/auth/forgot-password' },
    RESET_PASSWORD: { title: 'Reset Password', path: '/auth/reset-password' },
  },
  DASHBOARD: {
    HOME: { title: 'Dashboard Home', path: '/dashboard/' },
    PROJECTS: {
      PROJECTS: { title: 'My Projects', path: '/dashboard/projects/' },
      CABINETS: { title: 'Edit Cabinets', path: '/dashboard/projects/[id]/cabinets/' },
      NEW: { title: 'New Project', path: '/dashboard/projects/new/' },
      VIEW: { title: 'View Project', path: '/dashboard/projects/view/' },
    },
    TEAM: { title: 'Team', path: '/dashboard/team/' },
    ORDERS: { title: 'Orders', path: '/dashboard/orders/' },
    FAQ: { title: 'Frequently Asked Questions', path: '/dashboard/faq/' },
    DOCUMENTS: { title: 'Documents', path: '/dashboard/documents/' },
    SETTINGS: {
      SETTINGS: { title: 'Account Settings', path: '/dashboard/settings/' },
      PROFILE: { title: 'Profile', path: '/dashboard/settings/profile/' },
      SECURITY: { title: 'Security', path: '/dashboard/settings/security/' },
      ACCOUNT: { title: 'Account Info', path: '/dashboard/settings/account/' },
      NOTIFICATIONS: { title: 'Notifications', path: '/dashboard/settings/notifications/' },
    },
  },
  ADMIN: {
    DASHBOARD: { title: 'Admin Dashboard', path: '/admin/' },
    LEADS: { title: 'Leads', path: '/admin/leads/' },
    PROJECTS: { title: 'Projects', path: '/admin/projects/' },
    USERS: { title: 'Users', path: '/admin/users/' },
    SETTINGS: { title: 'Settings', path: '/admin/settings/' },
    FAQ: { title: 'FAQ', path: '/admin/faq/' },
    DOCUMENTS: { title: 'Documents', path: '/admin/documents/' },
    ORDERS: { title: 'Orders', path: '/admin/orders/' },
  },
  NOT_FOUND: { title: 'Page Not Found', path: '/404' },
};
